name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and deploy project
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - name: Setup nix
        uses: cachix/install-nix-action@v31.8.2
      - name: Build project
        run: |
          nix-shell --pure --command 'tailwindcss -i src/css/base.css -o src/css/compiled.css -m && ./dist.py'
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan "${{ vars.SSH_HOST }}" > ~/.ssh/known_hosts
      - name: Clean old files
        run: |
          ssh "${{ vars.SSH_USERNAME }}@${{ vars.SSH_HOST }}" "bash -c 'rm -rf ${{ vars.DEPLOY_DIR }}/* ${{ vars.DEPLOY_DIR }}/.[!.]* ${{ vars.DEPLOY_DIR }}/..?*'"
          scp -r dist/* "${{ vars.SSH_USERNAME }}@${{ vars.SSH_HOST }}:${{ vars.DEPLOY_DIR }}"
      - name: Copy files
        run: |
          scp Caddyfile "${{ vars.SSH_USERNAME }}@${{ vars.SSH_HOST }}:${{ vars.CADDY_PATH }}"
          ssh "${{ vars.SSH_USERNAME }}@${{ vars.SSH_HOST }}" "bash -c 'sudo systemctl restart caddy.service'"
